### ISSUE TITLE
Add ability to specify the directory of sound files. Do not change the sound source to earpiece

### ISSUE THREAD

**Issue by EternallLight** [Switch168/cordova-plugin-system-sound-services#1]
Hello,

I'm building a telephony app using [cordova-plugin-iosrtc](https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc), and, as you wrote in README, playing DTMF sounds in an HTML5 audio player or [cordova-plugin-media](https://github.com/apache/cordova-plugin-media) makes call sound disappear. Your plugin does the job great and allows to get rid of annoying music player in Control Panel (which appears when playing any sounds with HTML5 audio), but there are still a couple of improvements that would be nice to have.

1. Do not force the sound to use the earpiece. I use the [audio-toggle](https://github.com/alongubkin/audiotoggle) plugin to switch between earpiece and speaker, and when I play DTMF in speaker mode, the sound automatically goes back to the earpiece.

2. Allow specifying a path to the folder with sound files. By default, the plugin assumes that the sound files are in the root folder of the project. Before installing it, I had my sounds in `www/sounds`, and have no intention to move it. 

I am going to submit a pull request which covers both of these issues. 
Please review and let me know what you think.

Thanks,
Andrey

**Comment by andrewvmail** [comment]
Thanks for contributing! @EternallLight will review let you know

**Comment by andrewvmail** [comment]
Hey sorry took a while to get to this. Looks and merged
